### ISSUE TITLE
选中某一个子节点,然后点击穿梭按钮,所有数据都穿梭过去

### ISSUE THREAD

**Issue by xumeng31415926** [zshuhao/vue-element-tree-transfer#2]
第一次选中的某一个节点,点击穿梭,然后所有的节点信息都会穿梭到右边,然后在选中一个节点的,穿梭到左边,需要点击好几次才可以成,同时也会把所有节点信息给传过去

**Comment by zshuhao** [comment]
感谢关注，是这样的，选择父节点则包括父节点以及子节点都会穿梭到右侧；之后往左侧穿梭时，如果选择一个子节点穿梭到左侧，那么同时传到左侧的节点信息有：选中的子节点，它的父节点。因为此时父节点下的子节点并不是全选，所以也将它的信息也去掉了

**Comment by zshuhao** [comment]
@xumeng31415926 感谢关注，是这样的，选择父节点则包括父节点以及子节点都会穿梭到右侧；之后往左侧穿梭时，如果选择一个子节点穿梭到左侧，那么同时传到左侧的节点信息有：选中的子节点，它的父节点。因为此时父节点下的子节点并不是全选，所以也将它的信息也去掉了

**Comment by xumeng31415926** [comment]
嗯嗯,谢谢解答,那我该如何才能将所有的信息展示出来呢?同时我还有一个这样的需求,页面进入,一边所有权限(即节点信息),另一边是该用户享有的权限(即部分节点),然后助穿梭框给用户增加或减少权限(即左右穿梭节点),您这个项目可以实现吗?如果可以需要怎么样去修改呢

**Comment by zshuhao** [comment]
@xumeng31415926 如果说想选择节点添加到右侧后，左侧依然保持全部的权限信息（即完整的树形结构），目前这个组件是没办法实现的😂。现在的是节点移动到右侧后，左侧就会去掉对应的节点。你可以在`examples`目录下查看组件的使用方法。我当时搞这个也是为了满足业务需求，并没有太多的功能配置项。你可以拉下代码试着改一下或者寻找更优秀的组件😎

**Comment by xumeng31415926** [comment]
右侧的内容是value数组来存放的吧,那么如果在右侧的穿梭框内(即value数组内存放数据)预设数据,就应该可以达到效果(左边全部, 右边拥有的权限)

**Comment by zshuhao** [comment]
@xumeng31415926 是的，value中存放的就是右侧显示的数据，但是左侧并不是全部，左右两侧数据加起来才是全部。我这里保留了和elementUI中一样的逻辑，从左侧添加到右侧，那么左侧就去掉对应的节点。要想有你说的那种效果，只能再改代码了。添加到右侧的时候不要删除左侧的数据，复制就可以了

**Comment by xumeng31415926** [comment]
那么怎么获取value数组中的值呢?

**Comment by xumeng31415926** [comment]
牛逼呀老哥  ,子组件身上也可以v-model获取他的值吗?

**Comment by zshuhao** [comment]
@xumeng31415926 不是很理解你说的这个value是那个，你如果是使用vue的话，value定义在data中，直接可以取到的。它和组件使用v-model绑定，数据是实时变化的

**Comment by zshuhao** [comment]
@xumeng31415926 `v-model`和子组件`transfer-panel`是没有关联绑定的，通过`this.$emit('input', value)`，就可以修改`v-model`绑定的值了

**Comment by xumeng31415926** [comment]
就是存放右边数据的value 数组呀,我刚才试了下可以返回的是节点的 id

**Comment by zshuhao** [comment]
@xumeng31415926 是滴

**Comment by xumeng31415926** [comment]
如果说这是返回的节点的id,那么我通过value去预设也是行不通的啦

**Comment by zshuhao** [comment]
@xumeng31415926 你预设右侧数据的时候，给value赋的值，也应该是节点的id。这个在实际开发中，应该是约定好的，和后端交互时都是传id的吧

**Comment by xumeng31415926** [comment]
是的,在value数组中预设节点的id,就可以在右侧显示当前用户的权限,老哥牛逼

**Comment by zshuhao** [comment]
@xumeng31415926 哈哈，能帮到你就行，互相沟通学习

**Comment by xumeng31415926** [comment]
感谢大佬,这么耐心的给我解答,笔芯,哈哈哈
